[project]
name = "palindrome"
version = "0.1.0"
description = "The palindrome package"
license = "MIT"

[remote]
author = "aleo"

[target]
curve = "bls12_377"
proving_system = "groth16"

[dependencies]
# none
