[package]
name = "leo-lang"
version = "1.5.3"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "The Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "web-programming" ]
include = [ "Cargo.toml", "leo", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[lib]
path = "leo/lib.rs"

[[bin]]
name = "leo"
path = "leo/main.rs"

[workspace]
members = [
  "asg",
  "asg-passes",
  "ast",
  "ast-passes",
  "compiler",
  "errors",
  "grammar",
  "imports",
  "input",
  "linter",
  "package",
  "parser",
  "state",
  "stdlib",
  "synthesizer",
  "test-framework",
  "wasm"
]

[dependencies.leo-ast]
path = "./ast"
version = "1.5.3"

[dependencies.leo-compiler]
path = "./compiler"
version = "1.5.3"

[dependencies.leo-errors]
path = "./errors"
version = "1.5.3"

[dependencies.leo-imports]
path = "./imports"
version = "1.5.3"

[dependencies.leo-input]
path = "./input"
version = "1.5.3"

[dependencies.leo-package]
path = "./package"
version = "1.5.3"

[dependencies.leo-parser]
path = "./parser"
version = "1.5.3"

[dependencies.leo-state]
path = "./state"
version = "1.5.3"

[dependencies.leo-stdlib]
path = "./stdlib"
version = "1.5.3"

[dependencies.leo-synthesizer]
path = "./synthesizer"
version = "1.5.3"

[dependencies.snarkvm-algorithms]
version = "0.7.9"

[dependencies.snarkvm-curves]
version = "0.7.9"
default-features = false

[dependencies.snarkvm-gadgets]
version = "0.7.9"
default-features = false

[dependencies.snarkvm-r1cs]
version = "0.7.9"
default-features = false

[dependencies.snarkvm-utilities]
version = "0.7.9"

[dependencies.structopt]
version = "0.3"

[dependencies.clap]
version = "2.33.3"

[dependencies]
color-backtrace = "0.5.1"

[dependencies.colored]
version = "2.0"

[dependencies.dirs]
version = "4.0.0"

[dependencies.console]
version = "0.15.0"

[dependencies.from-pest]
version = "0.3.1"

[dependencies.indexmap]
version = "1.7"
features = ["serde"]

[dependencies.lazy_static]
version = "1.4.0"

[dependencies.notify]
version = "4.0.17"

[dependencies.rand]
version = "0.8"

[dependencies.rand_core]
version = "0.6.3"

[dependencies.reqwest]
version = "0.11.6"
features = [ "blocking", "json", "multipart" ]

[dependencies.self_update]
version = "0.27.0"
features = [ "archive-zip" ]

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.serde_json]
version = "1.0"

[dependencies.toml]
version = "0.5"

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.3.1"
features = [ "fmt" ]

[dependencies.zip]
version = "0.5"

[target."cfg(windows)".dependencies.ansi_term]
version = "0.12.1"

[dev-dependencies.rusty-hook]
version = "0.11.2"

[dev-dependencies.assert_cmd]
version = "2.0.2"

[dev-dependencies.test_dir]
version = "0.1.0"

[features]
default = [ ]
ci_skip = [ "leo-compiler/ci_skip" ]
noconfig = [ ]

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 0
debug-assertions = true
debug = true
