[project]
name = "linear-regression"
version = "0.1.0"
description = "The linear-regression package"
license = "MIT"

[remote]
author = "aleo"

[target]
curve = "bls12_377"
proving_system = "groth16"
